# Generated by Django 3.0.5 on 2020-09-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerbar', '0016_auto_20200923_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(default='restaurant', max_length=50),
        ),
    ]
